// <auto-generated />
using System;
using EcommerceBackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240413230444_ShoesOrdersEntity")]
    partial class ShoesOrdersEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceBackEnd.Entity.OrdersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrdersDBTable");
                });

            modelBuilder.Entity("EcommerceBackEnd.Entity.ShoesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoesDBTable");
                });

            modelBuilder.Entity("EcommerceBackEnd.Entity.ShoesOrdersEntity", b =>
                {
                    b.Property<int>("ShoesId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("ShoesId", "OrderId");

                    b.HasIndex("OrdersId");

                    b.ToTable("ShoesOrdersDBTable");
                });

            modelBuilder.Entity("EcommerceBackEnd.Entity.ShoesOrdersEntity", b =>
                {
                    b.HasOne("EcommerceBackEnd.Entity.OrdersEntity", "Orders")
                        .WithMany()
                        .HasForeignKey("OrdersId");

                    b.HasOne("EcommerceBackEnd.Entity.ShoesEntity", "Shoes")
                        .WithMany()
                        .HasForeignKey("ShoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
